### ISSUE TITLE
Non-empty collection can be deleted without force

### ISSUE THREAD

**Issue by dbrandenstein** [ArunaStorage/ArunaServer#33]
### Describe the bug
A collection which contains an object can be deleted without using force.

### To Reproduce
1. Create a collection and add an object to it
2. Delete the collection with force=false
3. The collection is deleted successfully

### Expected behavior
Without using force a delete should only be possible when a collection is empty.

**Comment by St4NNi** [comment]
Hi,

Thanks for reporting these issues, this should be fixed by [4cd4bc7](https://github.com/ArunaStorage/ArunaServer/commit/4cd4bc7445798efd8215efbe2963b51cd171e48c) . The deletion logic was "too smart" because it checked if the object was only referenced in this specific collection which allowed deletion without `force`.

Now this behaviour will only apply to objects in the staging phase but NOT for available / finished objects. Will close this for now, feel free to reopen it if you detect any related bugs.

BR

**Comment by St4NNi** [comment]
Weird, we should definetly improve the tests to cover these cases. Will reopen this for now.

**Comment by St4NNi** [comment]
Thanks again. This was indeed a bug, but somewhat unrelated to the previous bugs. With [df7b0ab](https://github.com/ArunaStorage/ArunaServer/commit/df7b0aba73969e36f39752ae1c4f8de1813fa784) we implemented a test to check for this false behaviour and also fixed the underlying issue. 

Will close this again, hopefully for the last time, feel free to comment if something is still wrong.
